apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-replication-controller
  labels:
    app: flask-app
spec:
  replicas: 3 # Desired number of replicas
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: docker.io/rachit798/flask-todo-app:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
